---
title: Exploratory Data Analysis
---


```{r load_libraries}

library(tidyverse)

library(forecast)

library(lubridate)

library(forcats)

library(slider)

library(tidymodels)


```


```{r setup}

theme_set(theme_bw())

plot_eval = FALSE

models_list = list()

```


```{r Import_data}

raw_df = read_csv(paste0(file.path(Sys.getenv("USERPROFILE"),
                                fsep = "\\"),                      "\\OneDrive - Bank Of Israel\\Data\\Asaf\\SPX.csv"))

spy = raw_df %>%
  rename_all(~tolower(.)) %>%
  mutate(date = mdy(date)) %>%
  mutate_if(~is.character(.), ~as.numeric(.))

```


## Summary stats

```{r plot_features_hist}

spy %>% 
  select(-date) %>% 
  pivot_longer(everything()) %>% 
  ggplot(aes(x = value)) + 
  geom_histogram() + 
  facet_wrap(~name, scales = "free")



```


```{r plot_features_timeseries, eval=plot_eval}

spy %>% 
  pivot_longer(-date) %>% 
  ggplot(aes(x = date, y = value)) + 
  geom_line() + 
  facet_wrap(~name, scales = "free")

```


```{r Preprocessing}


# Smoothing outliers
spy = spy %>% 
  mutate(across(c("indx_weighted_book_val",
                  "current_ev_to_book_value"),
                .fns = ~ slide_dbl(.,
                                   median,
                                   .before = 70,
                                   .after = 70)
                ))


# Difference non stationary features

spy = spy %>% 
  mutate(across(-date, ~c(NA, diff(log(.)))))


# Shift spx one day forward

spy = spy %>% 
  mutate(spx_index = lead(spx_index))


# Transform outcome to categorical

spy = spy %>% 
  mutate(market_dir = if_else(spx_index > 0, "up", "down")) %>% 
  mutate(market_dir = as_factor(market_dir))

# Filter complete cases

spy = spy %>% 
  filter(complete.cases(.))

```


```{r Feature_engineering, eval=FALSE}

# Calculate time periods

spy = spy %>%
  mutate(ret_10 = slide_dbl(spx_index,~diff(log(.x[c(1,10)])),
                            .before = 9,
                              .complete = TRUE)) %>%
  mutate(ret_15 = slide_dbl(spx_index,~diff(log(.x[c(1,15)])),
                            .before = 14,
                             .complete = TRUE)) %>%
  mutate(ret_30 = slide_dbl(spx_index,~diff(log(.x[c(1,30)])),
                            .before = 29,
                              .complete = TRUE))

# Convert ret 10 to binary

spy = spy %>% 
  mutate(ret_10_low = as.numeric(ret_10 < -0.05))


# Bin returns distribution

spy = spy %>% 
  mutate(ret_10_cat = cut(
    ret_10,
    breaks = c(-Inf,-0.1,-0.05,0,0.05,0.1,Inf),
    labels = c("10-","-10_-5","-5_0","0-5","5-10","10+"),
    ordered_result = TRUE))

```


```{r plot_features_timeseries,eval=plot_eval}

spy %>% 
  pivot_longer(-date) %>% 
  ggplot(aes(x = date, y = value)) + 
  geom_line() + 
  facet_wrap(~name, scales = "free")

```



```{r plot_ret_dist, eval=FALSE}

ggplot(spy, aes(x = date, y = ret_10)) + 
  geom_line() + 
  labs(x = "", y = "", title = "Returns (10 day period)") + 
  scale_y_continuous(
    labels = scales::percent_format(accuracy = 0.01)) + 
  geom_hline(yintercept = -0.05, color = "blue",
             linetype = "dashed") + 
  geom_point(data = spy %>% 
               filter(ret_10 < -0.05),
             aes(x = date, y = -0.05), color = "red") + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))

ggplot(spy, aes(x = ret_10)) + 
  geom_density() + 
  labs(x = "", y = "", title = "Returns (10 day period)") + 
  scale_x_continuous(labels = scales::percent_format(accuracy = 0.01)) +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))

ret_cat_dist = table(spy$ret_10_cat) %>% 
         as.data.frame()

ggplot(ret_cat_dist, aes(x = Var1, y = Freq)) + 
  geom_col() + 
  geom_text(aes(x = Var1, y = Freq,
                label = scales::percent(Freq / sum(Freq),accuracy = 0.1)),
            color = "magenta", vjust = -1) + 
  labs(x = "Return bins", y = "", title = "Frequency of return bins") + 
  scale_y_continuous(labels = scales::comma_format(),
                     limits = c(0,max(ret_cat_dist$Freq) * 1.05)) +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))

rm(ret_cat_dist)

```


```{r fit models}

models_list$linear_reg = linear_reg() %>% 
  set_engine("lm")

models_list$logit_reg = logistic_reg() %>% 
  set_engine("glm")




```


```{r train_set_predictions}


```


```{r rolling_cross_validation}

roll_grid = rolling_origin(spy,initial = 360,assess = 1)

roll_pred = map(roll_grid$splits[sample(1:nrow(roll_grid),500)], function(temp_split){
  
  train_set = analysis(temp_split)
  
  test_set = assessment(temp_split)
  
  linear_pred = models_list$linear_reg %>% 
    fit(spx_index ~ ., data = train_set) %>% 
    predict(new_data = test_set) %>% 
    mutate(return = test_set$spx_index) %>% 
    rename(ret_pred = .pred)
  
  logit_pred = models_list$logit_reg %>% 
    fit(market_dir ~ ., data = train_set) %>% 
    predict(new_data = test_set) %>% 
    mutate(market_dir = test_set$market_dir) %>% 
    rename(market_dir_pred = .pred_class)
  
  return(list(data.frame(date = test_set$date),
              linear_pred, logit_pred) %>% 
           bind_cols())

  
})

roll_pred = roll_pred %>% 
  bind_rows()


rmse = roll_pred %>% 
  select(return, ret_pred) %>% 
  rmse(truth = return, estimate = ret_pred)

accuracy_score = roll_pred %>% 
  select(market_dir, market_dir_pred) %>% 
  accuracy(truth = market_dir, estimate = market_dir_pred)

```

