---
title: Exploratory Data Analysis
---


```{r, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```


```{r load_libraries}

devtools::load_all()

library(tidyverse)

library(forecast)

library(lubridate)

library(forcats)

library(slider)

library(zoo)



```


```{r setup}

theme_set(theme_bw() +
            theme(legend.position = "bottom",
                  legend.title = element_blank()))

```


```{r import_data}

data("sp_data")

```


```{r feature_engineering}

sp_data = sp_data %>% 
  mutate(sp_spread = (t12_eps_aggte / spx_index) * 100 - us_gov_yield_10_y) %>% 
  mutate(sp_ret = c(NA, diff(log(spx_index)))) %>% 
  mutate(sp_drawdown = calculate_drawdown(spx_index))

```


# S&P 500

```{r plot_sp}

sp_data %>% 
ggplot(aes(x = date, y = spx_index)) +
  geom_line() +
  xlab(NULL) + ylab(NULL) + ggtitle("S&P 500 index")

```

The S&P index was trending upwards since the 90's, took a hit in 2000,
rebounded and  took another hit in 2008. Since the GFC the index is going up.

```{r}

sp_data %>% 
  mutate(dist_from_min = slide_dbl(.x = sp_spread,
                                   .f = ~ log(.x[50] - min(.x, na.rm = TRUE) + 1),
                                   .before = 49),
         next_year_ret = lead(spx_index,365) / spx_index - 1) %>% 
  ggplot(aes(x = dist_from_min, y = next_year_ret)) + 
  geom_point() + 
  geom_smooth()
  xlab(NULL) + ylab(NULL) + 
  ggtitle("Distance from local min vs Next year return")

```



Let's look at the drawdown of the index

```{r plot_drawdown}

sp_data %>% 
  ggplot(aes(x = date, y = sp_drawdown)) + 
  geom_line() + 
  geom_hline(yintercept = 0, linetype = "dashed", color = "blue") + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  xlab(NULL) + ylab(NULL) + ggtitle("S&P 500 drawdown")

```


```{r plot_drawdown_vs_spread}

event_df = sp_data %>% 
  select(date, sp_drawdown) %>% 
  filter(complete.cases(.)) %>% 
  mutate(indicator = as.numeric(sp_drawdown < -0.1)) %>% 
  mutate(diff = c(NA,diff(indicator))) %>% 
  filter(diff %in% c(1,-1)) %>% 
  mutate(diff = if_else(diff == 1,"start_date","end_date")) %>% 
  select(-indicator, -sp_drawdown) %>% 
  slice(-nrow(.)) %>% 
  pivot_wider(names_from = "diff", values_from = "date",values_fn = list) %>% 
  unnest(cols = c("start_date", "end_date")) %>% 
  mutate(across(everything(), ymd))

sp_data %>% 
  ggplot(aes(x = date, y = sp_spread)) + 
  geom_line() + 
  geom_rect(data = event_df,
            mapping = aes(xmin = start_date, xmax = end_date,
                          ymin = -Inf, ymax = Inf),
            inherit.aes = FALSE, fill = "red", alpha = 0.2) + 
  xlab(NULL) + ylab(NULL) + ggtitle("S&P spread")
  



```


```{r plot_drawdown_vs_spread_monthly}

lead_step = 4

sp_data %>% 
  group_by(date = as.yearmon(date)) %>% 
  summarise(sp_spread = mean(sp_spread, na.rm = TRUE)) %>% 
  ggplot(aes(x = date, y = lead(sp_spread,lead_step))) + 
  geom_line() + 
  geom_rect(data = event_df %>% 
              mutate(across(everything(), as.yearmon)),
            mapping = aes(xmin = start_date, xmax = end_date,
                          ymin = -Inf, ymax = Inf),
            inherit.aes = FALSE, fill = "red", alpha = 0.2) + 
  xlab(NULL) + ylab(NULL) + 
  ggtitle(paste0("S&P spread (lead ",
                 lead_step," months) at monthly frequency"))


rm(lead_step)  



```

